name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildLinux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x','6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Linux
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  buildWindows:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x','6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Linux
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  buildMac:

    runs-on: macos-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x','6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Linux
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal